apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: complex
data:
  REDIS_HOST: redis-cluster-ip-service
  REDIS_PORT: "6379"
  PGUSER: postgres
  PGHOST: postgres-cluster-ip-service 
  PGPORT: "5432"
  PGDATABASE: postgres
  